feat: add new grub theme
linuxdeepin/dde-api pull request #122
Opened 2024-09-25 07:25 UTC by wxphaha

add new grub theme

Log:  add new grub theme

2024-09-25 08:45 UTC, zsien requested changes

2024-09-25 08:45 UTC, zsien commented on adjust-grub-theme/main.go
> +func ParseOSVersionFile(filePath string) (string, error) {
1. 首字母小写
2. 这个函数的作用是获取 SystemName 而不是返回解析 os-version 的结果

2024-09-25 08:45 UTC, zsien commented on adjust-grub-theme/main.go
> +	var backGroundFileName, themeBackGroundFileName string
background 和 filename 都是一个单词，不需要 backGround 和 fileName

2024-09-25 08:45 UTC, zsien commented on adjust-grub-theme/main.go
> +	logger.Warning(err)
这里获取不到 546 行的 err

2024-09-25 09:44 UTC, wxphaha commented on adjust-grub-theme/main.go
> +func ParseOSVersionFile(filePath string) (string, error) {
Thanks, modify to getSystemNameFromOSVersionFile

2024-09-25 09:44 UTC, wxphaha commented on adjust-grub-theme/main.go
> +	var backGroundFileName, themeBackGroundFileName string
Thanks, modified

2024-09-25 09:44 UTC, wxphaha commented on adjust-grub-theme/main.go
> +	logger.Warning(err)
Thanks, modified

2024-09-26 02:44 UTC, zsien approved these changes

2024-09-26 03:44 UTC, Zeno-sole commented
/integrate

2024-09-26 07:02 UTC, Zeno-sole commented
/merge

2024-09-26 07:05 UTC, yixinshark commented
/forcemerge

2024-09-26 07:05 UTC, merged